/* eslint-disable */
/**
 * This file is automatically generated by swagger-to-ts. Do not modify it manually.
 */

import axios from './request';
import type { RequestConfig } from './types';
import type { NSGetBasicDaily, NSGetBasicStock } from './services.types.ts';
/**
 * 接口名称：每日交易数据
 *
 * @description 接口路径：/basic/daily
 * @description 接口分组：基础数据
 */
export const getBasicDaily = (params: NSGetBasicDaily.IParams, config: RequestConfig = {}) =>
  axios.get<void>('/basic/daily', { params }, config);
/**
 * 接口名称：每日交易数据
 *
 * @description 接口路径：/basic/stock
 * @description 接口分组：基础数据
 */
export const getBasicStock = (params: NSGetBasicStock.IParams, config: RequestConfig = {}) =>
  axios.get<void>('/basic/stock', { params }, config);
