/* eslint-disable */
/**
 * This file is automatically generated by swagger-to-ts. Do not modify it manually.
 */
/**
 * 类型名称：批量创建Daily
 *
 * @description 接口路径：/source/daily/bulk-create
 * @description 接口分组：源数据 - Daily模块
 */
export namespace NSPostSourceDailyBulkCreate {
  export type IBody = string[];
}
/**
 * 类型名称：清空Daily
 *
 * @description 接口路径：/source/daily/clear
 * @description 接口分组：源数据 - Daily模块
 */
export namespace NSDeleteSourceDailyClear {}
/**
 * 类型名称：创建Daily
 *
 * @description 接口路径：/source/daily/create
 * @description 接口分组：源数据 - Daily模块
 */
export namespace NSPostSourceDailyCreate {
  export interface IBody {
    /**
     * 股票代码（包含交易所）
     */
    tsCode?: string;
    /**
     * 股票名称
     */
    name?: string;
    /**
     * 交易日期
     */
    tradeDate?: string;
    /**
     * 涨停价
     */
    upLimit?: string;
    /**
     * 跌停价
     */
    downLimit?: string;
    /**
     * 开盘价
     */
    open?: string;
    /**
     * 最高价
     */
    high?: string;
    /**
     * 最低价
     */
    low?: string;
    /**
     * 收盘价
     */
    close?: string;
    /**
     * 昨收价
     */
    preClose?: string;
    /**
     * 涨跌额
     */
    change?: string;
    /**
     * 涨跌幅
     */
    pctChg?: string;
    /**
     * 成交量（手）
     */
    vol?: string;
    /**
     * 成交额（万元）
     */
    amount?: string;
    /**
     * 换手率
     */
    turnoverRate?: string;
    /**
     * 换手率（自由流通股）
     */
    turnoverRateF?: string;
    /**
     * 量比
     */
    volumeRatio?: string;
    /**
     * 市盈率（总市值/总利润）
     */
    pe?: string;
    /**
     * 市盈率（TTM）
     */
    peTtm?: string;
    /**
     * 市净率（总市值/净资产）
     */
    pb?: string;
    /**
     * 市销率
     */
    ps?: string;
    /**
     * 市销率（TTM）
     */
    psTtm?: string;
    /**
     * 股息率（%）
     */
    dvRatio?: string;
    /**
     * 股息率（TTM）（%）
     */
    dvTtm?: string;
    /**
     * 总股本（万股）
     */
    totalShare?: string;
    /**
     * 流通股本（万股）
     */
    floatShare?: string;
    /**
     * 自由流通股本（万股）
     */
    freeShare?: string;
    /**
     * 总市值（万元）
     */
    totalMv?: string;
    /**
     * 流通市值（万元）
     */
    circMv?: string;
    [k: string]: any;
  }
}
/**
 * 类型名称：获取Daily列表
 *
 * @description 接口路径：/source/daily/list
 * @description 接口分组：源数据 - Daily模块
 */
export namespace NSGetSourceDailyList {
  export interface IParams {
    /**
     * pageNum
     */
    pageNum: number;
    /**
     * pageSize
     */
    pageSize: number;
    /**
     * field
     */
    field: string;
    /**
     * order
     */
    order: string;
    /**
     * 股票代码（包含交易所）
     */
    tsCode: string;
    /**
     * 交易日期
     */
    tradeDate: string;
    /**
     * 开始时间
     */
    startDate: string;
    /**
     * 结束时间
     */
    endDate: string;
  }
  export interface IRes {
    items: {
      /**
       * 股票代码（包含交易所）
       */
      tsCode: string;
      /**
       * 股票名称
       */
      name: string;
      /**
       * 交易日期
       */
      tradeDate: string;
      /**
       * 涨停价
       */
      upLimit: string;
      /**
       * 跌停价
       */
      downLimit: string;
      /**
       * 开盘价
       */
      open: string;
      /**
       * 最高价
       */
      high: string;
      /**
       * 最低价
       */
      low: string;
      /**
       * 收盘价
       */
      close: string;
      /**
       * 昨收价
       */
      preClose: string;
      /**
       * 涨跌额
       */
      change: string;
      /**
       * 涨跌幅
       */
      pctChg: string;
      /**
       * 成交量（手）
       */
      vol: string;
      /**
       * 成交额（万元）
       */
      amount: string;
      /**
       * 换手率
       */
      turnoverRate: string;
      /**
       * 换手率（自由流通股）
       */
      turnoverRateF: string;
      /**
       * 量比
       */
      volumeRatio: string;
      /**
       * 市盈率（总市值/总利润）
       */
      pe: string;
      /**
       * 市盈率（TTM）
       */
      peTtm: string;
      /**
       * 市净率（总市值/净资产）
       */
      pb: string;
      /**
       * 市销率
       */
      ps: string;
      /**
       * 市销率（TTM）
       */
      psTtm: string;
      /**
       * 股息率（%）
       */
      dvRatio: string;
      /**
       * 股息率（TTM）（%）
       */
      dvTtm: string;
      /**
       * 总股本（万股）
       */
      totalShare: string;
      /**
       * 流通股本（万股）
       */
      floatShare: string;
      /**
       * 自由流通股本（万股）
       */
      freeShare: string;
      /**
       * 总市值（万元）
       */
      totalMv: string;
      /**
       * 流通市值（万元）
       */
      circMv: string;
      [k: string]: any;
    }[];
    meta: {
      itemCount: number;
      totalItems: number;
      itemsPerPage: number;
      totalPages: number;
      currentPage: number;
      [k: string]: any;
    };
    [k: string]: any;
  }
}
/**
 * 类型名称：获取Daily详情
 *
 * @description 接口路径：/source/daily/{id}
 * @description 接口分组：源数据 - Daily模块
 */
export namespace NSGetSourceDaily {
  export interface IRes {
    /**
     * 股票代码（包含交易所）
     */
    tsCode: string;
    /**
     * 股票名称
     */
    name: string;
    /**
     * 交易日期
     */
    tradeDate: string;
    /**
     * 涨停价
     */
    upLimit: string;
    /**
     * 跌停价
     */
    downLimit: string;
    /**
     * 开盘价
     */
    open: string;
    /**
     * 最高价
     */
    high: string;
    /**
     * 最低价
     */
    low: string;
    /**
     * 收盘价
     */
    close: string;
    /**
     * 昨收价
     */
    preClose: string;
    /**
     * 涨跌额
     */
    change: string;
    /**
     * 涨跌幅
     */
    pctChg: string;
    /**
     * 成交量（手）
     */
    vol: string;
    /**
     * 成交额（万元）
     */
    amount: string;
    /**
     * 换手率
     */
    turnoverRate: string;
    /**
     * 换手率（自由流通股）
     */
    turnoverRateF: string;
    /**
     * 量比
     */
    volumeRatio: string;
    /**
     * 市盈率（总市值/总利润）
     */
    pe: string;
    /**
     * 市盈率（TTM）
     */
    peTtm: string;
    /**
     * 市净率（总市值/净资产）
     */
    pb: string;
    /**
     * 市销率
     */
    ps: string;
    /**
     * 市销率（TTM）
     */
    psTtm: string;
    /**
     * 股息率（%）
     */
    dvRatio: string;
    /**
     * 股息率（TTM）（%）
     */
    dvTtm: string;
    /**
     * 总股本（万股）
     */
    totalShare: string;
    /**
     * 流通股本（万股）
     */
    floatShare: string;
    /**
     * 自由流通股本（万股）
     */
    freeShare: string;
    /**
     * 总市值（万元）
     */
    totalMv: string;
    /**
     * 流通市值（万元）
     */
    circMv: string;
    [k: string]: any;
  }
}
/**
 * 类型名称：更新Daily
 *
 * @description 接口路径：/source/daily/{id}
 * @description 接口分组：源数据 - Daily模块
 */
export namespace NSPutSourceDaily {
  export interface IBody {
    /**
     * 股票代码（包含交易所）
     */
    tsCode?: string;
    /**
     * 股票名称
     */
    name?: string;
    /**
     * 交易日期
     */
    tradeDate?: string;
    /**
     * 涨停价
     */
    upLimit?: string;
    /**
     * 跌停价
     */
    downLimit?: string;
    /**
     * 开盘价
     */
    open?: string;
    /**
     * 最高价
     */
    high?: string;
    /**
     * 最低价
     */
    low?: string;
    /**
     * 收盘价
     */
    close?: string;
    /**
     * 昨收价
     */
    preClose?: string;
    /**
     * 涨跌额
     */
    change?: string;
    /**
     * 涨跌幅
     */
    pctChg?: string;
    /**
     * 成交量（手）
     */
    vol?: string;
    /**
     * 成交额（万元）
     */
    amount?: string;
    /**
     * 换手率
     */
    turnoverRate?: string;
    /**
     * 换手率（自由流通股）
     */
    turnoverRateF?: string;
    /**
     * 量比
     */
    volumeRatio?: string;
    /**
     * 市盈率（总市值/总利润）
     */
    pe?: string;
    /**
     * 市盈率（TTM）
     */
    peTtm?: string;
    /**
     * 市净率（总市值/净资产）
     */
    pb?: string;
    /**
     * 市销率
     */
    ps?: string;
    /**
     * 市销率（TTM）
     */
    psTtm?: string;
    /**
     * 股息率（%）
     */
    dvRatio?: string;
    /**
     * 股息率（TTM）（%）
     */
    dvTtm?: string;
    /**
     * 总股本（万股）
     */
    totalShare?: string;
    /**
     * 流通股本（万股）
     */
    floatShare?: string;
    /**
     * 自由流通股本（万股）
     */
    freeShare?: string;
    /**
     * 总市值（万元）
     */
    totalMv?: string;
    /**
     * 流通市值（万元）
     */
    circMv?: string;
    [k: string]: any;
  }
}
/**
 * 类型名称：删除Daily
 *
 * @description 接口路径：/source/daily/{id}
 * @description 接口分组：源数据 - Daily模块
 */
export namespace NSDeleteSourceDaily {}
