import { utilityColors, uiColors, withAlpha } from '../colors';

// Compatibility aliases for existing Tailwind utility names.
export const EThemeColors = {
  colorTeal: utilityColors.teal,
  colorTeal78: withAlpha(utilityColors.teal, 0.78),
  colorTeal56: withAlpha(utilityColors.teal, 0.56),
  colorLightBlue: utilityColors['light-blue'],
  colorLightBlue78: withAlpha(utilityColors['light-blue'], 0.78),
  colorLightBlue56: withAlpha(utilityColors['light-blue'], 0.56),
  colorViolet: utilityColors.violet,
  colorViolet78: withAlpha(utilityColors.violet, 0.78),
  colorViolet56: withAlpha(utilityColors.violet, 0.56),
  colorPinkRed: utilityColors['pink-red'],
  colorPinkRed78: withAlpha(utilityColors['pink-red'], 0.78),
  colorPinkRed56: withAlpha(utilityColors['pink-red'], 0.56),
  colorOrange: utilityColors.orange,
  colorOrange78: withAlpha(utilityColors.orange, 0.78),
  colorOrange56: withAlpha(utilityColors.orange, 0.56),
  colorYellow: utilityColors.yellow,
  colorYellow78: withAlpha(utilityColors.yellow, 0.78),
  colorYellow56: withAlpha(utilityColors.yellow, 0.56),
  colorLightGreen: utilityColors['light-green'],
  colorLightGreen78: withAlpha(utilityColors['light-green'], 0.78),
  colorLightGreen56: withAlpha(utilityColors['light-green'], 0.56),
  colorLimeGreen: utilityColors['lime-green'],
  colorLimeGreen78: withAlpha(utilityColors['lime-green'], 0.78),
  colorLimeGreen56: withAlpha(utilityColors['lime-green'], 0.56),
  colorGrey: utilityColors.grey,
  colorGrey78: withAlpha(utilityColors.grey, 0.78),
  colorGrey56: withAlpha(utilityColors.grey, 0.56),
  colorBlack: utilityColors.black,
  colorBlack78: withAlpha(utilityColors.black, 0.78),
  colorBlack56: withAlpha(utilityColors.black, 0.56),
  colorWhite: uiColors.surface,
  colorTransparent: 'transparent',
};
